//! OpenAPI document — replaces `swaggo/swag` (the `// @title …` annotations in
//! `backend/main.go`). The raw spec is served at `GET /api-docs/openapi.json`; the
//! interactive Swagger UI is still deferred (see `docs/roadmap.md`). Every HTTP
//! operation from `main.rs::build_router` is registered in `paths(...)` below —
//! the test at the bottom cross-checks the operation count + key paths.

use utoipa::openapi::security::{ApiKey, ApiKeyValue, SecurityScheme};
use utoipa::{Modify, OpenApi};

use crate::models;

/// The kutup API description — mirrors the `// @title/@version/...` block in `main.go`.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Kutup API",
        version = "1.0.0",
        description = "Self-hosted, end-to-end encrypted file storage with federation. \
All file content and metadata are encrypted client-side; the server stores only ciphertext.",
        license(name = "AGPL-3.0-only", url = "https://www.gnu.org/licenses/agpl-3.0.html"),
    ),
    paths(
        // --- health ---
        crate::health,
        // --- auth + user ---
        crate::handlers::auth::get_public_settings,
        crate::handlers::auth::register,
        crate::handlers::auth::get_login_preflight,
        crate::handlers::auth::login,
        crate::handlers::auth::login_two_fa,
        crate::handlers::auth::get_recovery_preflight,
        crate::handlers::auth::recover,
        crate::handlers::auth::refresh,
        crate::handlers::auth::complete_setup,
        crate::handlers::sessions::logout,
        crate::handlers::sessions::list_sessions,
        crate::handlers::sessions::revoke_session,
        crate::handlers::sessions::revoke_other_sessions,
        crate::handlers::sessions::create_fork,
        crate::handlers::sessions::consume_fork,
        crate::handlers::sessions::put_local_key,
        crate::handlers::sessions::get_local_key,
        crate::handlers::auth::get_me,
        crate::handlers::auth::update_me,
        crate::handlers::storage::usage,
        crate::handlers::mail_keys::list_addresses,
        crate::handlers::contacts::list,
        crate::handlers::contacts::create,
        crate::handlers::contacts::update,
        crate::handlers::contacts::delete,
        crate::handlers::contacts::delete_many,
        crate::handlers::contacts::import,
        crate::handlers::contacts::emails,
        crate::handlers::contacts::list_groups,
        crate::handlers::contacts::create_group,
        crate::handlers::contacts::update_group,
        crate::handlers::contacts::delete_group,
        crate::handlers::mail_keys::add_key,
        crate::handlers::mail_keys::lookup_keys,
        crate::handlers::mail::list_messages,
        crate::handlers::mail::message_content,
        crate::handlers::mail::update_messages,
        crate::handlers::mail::delete_messages,
        crate::handlers::mail::counts,
        crate::handlers::mail::thread,
        crate::handlers::mail_send::create_draft,
        crate::handlers::mail_send::update_draft,
        crate::handlers::mail_send::add_draft_attachment,
        crate::handlers::mail_send::list_draft_attachments,
        crate::handlers::mail_send::draft_attachment_content,
        crate::handlers::mail_send::delete_draft_attachment,
        crate::handlers::mail_send::send,
        crate::handlers::mail_sending::own_status,
        crate::handlers::mail_sending::senders,
        crate::handlers::mail_sending::one,
        crate::handlers::mail_sending::update,
        crate::handlers::storage::version_ages,
        crate::handlers::storage::prune_versions,
        crate::handlers::auth::setup_totp,
        crate::handlers::auth::verify_totp,
        crate::handlers::auth::disable_totp,
        crate::handlers::auth::get_user_by_email,
        // --- collections ---
        crate::handlers::collections::list_collections,
        crate::handlers::collections::create_collection,
        crate::handlers::collections::get_collection,
        crate::handlers::collections::update_collection,
        crate::handlers::collections::delete_collection,
        crate::handlers::collections::update_collection_color,
        crate::handlers::collections::share_collection,
        crate::drive_federation::fetch_remote_user,
        crate::drive_federation::create_federated_share,
        crate::drive_federation_files::create_federated_file_share,
        crate::drive_federation_files::get_file_invite,
        crate::drive_federation_files::get_file_content,
        crate::drive_federation_files::get_file_state,
        crate::drive_federation_files::accept_file_share,
        crate::drive_federation_files::list_file_shares,
        crate::drive_federation_files::get_file_share,
        crate::drive_federation_files::proxy_file_content,
        crate::drive_federation_files::proxy_file_state,
        crate::drive_federation_files::remove_file_share,
        crate::drive_federation_files::get_folder_file_state,
        crate::drive_federation_files::proxy_folder_file_state,
        crate::drive_federation_albums::album_items,
        crate::drive_federation_albums::thumbnail,
        crate::drive_federation_albums::proxy_album_items,
        crate::drive_federation_albums::proxy_thumbnail,
        crate::drive_profile_keys::list_people,
        crate::maps::get_config,
        crate::live_locations::create,
        crate::live_locations::write,
        crate::live_locations::delete,
        crate::live_locations::read,
        crate::live_locations::federated_read,
        crate::maps::put_preferences,
        crate::ui_preferences::get_ui_preferences,
        crate::handlers::name_hashes::set_content_hash,
        crate::handlers::name_hashes::fill_name_hashes,
        crate::handlers::name_hashes::fill_top_level_name_hashes,
        crate::ui_preferences::put_ui_preferences,
        crate::photos::get_preferences,
        crate::photos::put_preferences,
        crate::photos::get_library,
        crate::albums::list,
        crate::albums::create,
        crate::albums::delete,
        crate::albums::items,
        crate::albums::add_items,
        crate::albums::remove_items,
        crate::albums::keys,
        crate::albums::leave,
        crate::handlers::shares::public_album_items,
        crate::handlers::shares::public_thumbnail,
        crate::photos::put_library,
        crate::maps::proxy,
        crate::maps::admin_get,
        crate::maps::admin_put,
        crate::drive_profile_keys::put_profile_key,
        crate::drive_profile_keys::receive_profile_key,
        // --- devices ---
        crate::handlers::devices::register,
        crate::handlers::devices::list,
        crate::handlers::devices::revoke,
        // --- tus resumable uploads ---
        crate::handlers::tus::create,
        crate::handlers::tus::patch,
        crate::handlers::tus::head,
        crate::handlers::tus::delete,
        // --- files ---
        crate::handlers::files::list_files,
        crate::handlers::files::list_all_files,
        crate::handlers::files::upload,
        crate::handlers::files::download,
        crate::handlers::files::download_original,
        crate::handlers::files::update_metadata,
        crate::handlers::files::delete,
        crate::handlers::files::claim_seed,
        // --- trash ---
        crate::handlers::trash::list,
        crate::handlers::trash::empty,
        crate::handlers::trash::destroy,
        crate::handlers::trash::restore,
        // --- file versions ---
        crate::handlers::file_versions::list,
        crate::handlers::file_versions::create,
        crate::handlers::folder_access::epochs,
        crate::handlers::folder_access::access,
        crate::handlers::folder_access::rotate,
        crate::handlers::folder_access::rekey,
        crate::handlers::file_shares::share_file,
        crate::handlers::file_shares::file_access,
        crate::handlers::file_shares::reseal,
        crate::handlers::file_shares::rotate,
        crate::handlers::file_shares::shared_with_me,
        crate::handlers::file_shares::pending,
        crate::handlers::file_shares::shared_by_me,
        crate::handlers::file_shares::set_sharing,
        crate::handlers::drive_move::move_file,
        crate::handlers::drive_move::move_collection,
        crate::handlers::file_versions::download,
        crate::handlers::file_versions::patch,
        crate::handlers::file_versions::delete,
        // --- file assets ---
        crate::handlers::file_assets::upload,
        crate::handlers::file_assets::download,
        crate::handlers::file_thumbnails::upload,
        crate::handlers::file_thumbnails::download,
        crate::handlers::file_thumbnails::delete,
        // --- collab WebSocket ---
        crate::handlers::collab::ws,
        // --- public shares ---
        crate::handlers::shares::create_public_share,
        crate::handlers::shares::get_public_share,
        crate::handlers::shares::list_public_share_files,
        crate::handlers::shares::public_share_epochs,
        crate::handlers::shares::download_public_share_file,
        crate::handlers::shares::public_share_state,
        // --- Drive federation (shared signed stack + per-share capability) ---
        crate::drive_federation::get_user,
        crate::drive_federation::get_invite,
        crate::drive_federation::list_files,
        crate::drive_federation::list_epochs,
        crate::drive_federation::proxy_list_epochs,
        crate::drive_federation::refresh_incoming_share,
        crate::drive_federation::upload_file,
        crate::drive_federation::download_file,
        crate::drive_federation::delete_file,
        crate::drive_federation::accept_incoming_share,
        crate::drive_federation::list_incoming_shares,
        crate::drive_federation::remove_incoming_share,
        crate::drive_federation::proxy_list_files,
        crate::drive_federation::proxy_download,
        crate::drive_federation::proxy_upload,
        crate::drive_federation::proxy_delete,
        // --- admin ---
        crate::handlers::admin::list_users,
        crate::handlers::admin::create_user,
        crate::handlers::admin::update_user,
        crate::handlers::admin::delete_user,
        crate::handlers::admin::force_disable_2fa,
        crate::handlers::admin::rotate_temp_password,
        crate::handlers::admin::wipe_user,
        crate::handlers::admin::get_stats,
        crate::handlers::admin::activity,
        crate::handlers::admin::activity_export,
        crate::handlers::admin::get_settings,
        crate::handlers::admin::update_settings,
        crate::handlers::admin::get_federation_control_plane,
        crate::handlers::admin::update_federation_policy,
        crate::handlers::admin::upsert_federation_domain_rule,
        crate::handlers::admin::delete_federation_domain_rule,
        crate::handlers::admin::get_federation_peer_evidence,
        crate::handlers::admin::verify_federation_peer,
        crate::handlers::admin::retry_federation_peer,
        crate::handlers::admin::bulk_retry_federation_peers,
        crate::handlers::admin::repin_federation_peer,
        crate::federation::discovery::public_discovery,
        crate::federation::discovery::public_identity_document,
        // --- chat (E2EE messaging — phase 2 of docs/research/11-federated-chat.md) ---
        crate::handlers::chat::register_device,
        crate::handlers::chat::list_devices,
        crate::handlers::chat::rename_device,
        crate::handlers::chat::revoke_device,
        crate::handlers::chat::publish_manifest,
        crate::handlers::chat::get_user_manifest,
        crate::handlers::chat::put_profile,
        crate::handlers::chat::get_own_profile,
        crate::handlers::chat::get_user_profile,
        crate::handlers::chat::replenish_keys,
        crate::handlers::chat::prekey_count,
        crate::handlers::chat::get_user_bundles,
        crate::handlers::chat::send_messages,
        crate::handlers::chat::sync_messages,
        crate::handlers::chat::drain_mailbox,
        crate::handlers::chat::ack_messages,
        crate::handlers::chat::create_ws_ticket,
        crate::handlers::chat_link_preview::fetch,
        crate::web_push::put_subscription,
        crate::calls::call_servers,
        crate::chat_mls::group_calls::token,
        crate::chat_mls::call_links::create,
        crate::chat_mls::call_links::list,
        crate::chat_mls::call_links::delete,
        crate::chat_mls::call_links::token,
        crate::chat_mls::call_links::update_info,
        crate::chat_mls::call_links::info,
        crate::chat_mls::call_link_waiting::set_waiting_room,
        crate::chat_mls::call_link_waiting::knock,
        crate::chat_mls::call_link_waiting::knock_status,
        crate::chat_mls::call_link_waiting::leave_knock,
        crate::chat_mls::call_link_waiting::knocks,
        crate::chat_mls::call_link_waiting::decide,
        crate::chat_mls::call_link_moderation::roles,
        crate::chat_mls::call_link_moderation::set_co_host,
        crate::chat_mls::call_link_moderation::remove_participant,
        crate::chat_mls::call_link_moderation::mute,
        crate::chat_mls::call_link_moderation::set_screen_share,
        crate::chat_mls::call_link_moderation::lock,
        crate::chat_mls::call_link_moderation::end,
        crate::chat_mls::call_link_history::list,
        crate::chat_mls::call_link_history::add,
        crate::chat_mls::call_link_history::remove,
        crate::chat_mls::call_link_history::clear,
        crate::web_push::delete_subscription,
        crate::handlers::chat::ws,
        crate::handlers::chat_backup::provision,
        crate::handlers::chat_backup::status,
        crate::handlers::chat_backup::append_segment,
        crate::handlers::chat_backup::list_segments,
        crate::handlers::chat_backup::stage_base,
        crate::handlers::chat_backup::commit_manifest,
        crate::handlers::chat_backup::download_base,
        crate::handlers::chat_backup::copy_media,
        crate::handlers::chat_backup::upload_media,
        crate::handlers::chat_backup::download_media,
        crate::handlers::chat_backup::reconcile_media,
        crate::chat_mls::policy::get_policy_history,
        crate::chat_mls::invite_links::call,
        // --- chat federation (signed server-to-server directory foundation) ---
        crate::chat_federation::get_user_bundles,
        crate::chat_federation::get_user_profile,
        crate::chat_federation::deliver_messages,
    ),
    components(schemas(
        kutup_chat_proto::InviteLinkCallV1,
        kutup_chat_proto::InviteLinkOperationV1,
        kutup_chat_proto::InviteLinkResultV1,
        kutup_chat_proto::InviteLinkRequestEntryV1,
        kutup_chat_proto::InviteRequestStatusV1,
        kutup_chat_proto::DirectChatSuiteId,
        kutup_chat_proto::EnvelopeType,
        kutup_chat_proto::EcPreKey,
        kutup_chat_proto::KemPreKey,
        kutup_chat_proto::RegisterChatDeviceRequest,
        kutup_chat_proto::RegisterChatDeviceResponse,
        kutup_chat_proto::RenameChatDeviceRequest,
        kutup_chat_proto::ReplenishKeysRequest,
        kutup_chat_proto::PreKeyCountResponse,
        kutup_chat_proto::AccountIdentitySuiteId,
        kutup_chat_proto::AccountManifestDriveKeysV1,
        kutup_chat_proto::AccountManifestDeviceV1,
        kutup_chat_proto::AccountManifestV1,
        kutup_chat_proto::AccountManifestPublicationV1,
        kutup_chat_proto::AccountManifestHistoryPageV1,
        kutup_chat_proto::PutChatProfileRequest,
        kutup_chat_proto::ChatProfileResponse,
        kutup_chat_proto::DevicePreKeyBundle,
        kutup_chat_proto::UserPreKeyBundlesResponse,
        kutup_chat_proto::OutgoingEnvelope,
        kutup_chat_proto::SendMessagesRequest,
        kutup_chat_proto::DeviceListMismatch,
        kutup_chat_proto::DeliveredEnvelope,
        kutup_chat_proto::MailboxPage,
        kutup_chat_proto::AckRequest,
        kutup_chat_proto::ChatWsServerMessage,
        kutup_chat_proto::ChatWsClientMessage,
        kutup_chat_proto::ChatWsTicketResponse,
        crate::handlers::chat_link_preview::LinkPreviewFetchRequest,
        crate::web_push::PushSubscriptionRequest,
        crate::calls::CallServersResponse,
        crate::calls::IceServer,
        crate::chat_mls::group_calls::GroupCallTokenRequest,
        crate::chat_mls::group_calls::GroupCallTokenResponse,
        crate::chat_mls::call_links::CreateCallLinkRequest,
        crate::chat_mls::call_links::CallLink,
        crate::chat_mls::call_links::CallLinkList,
        crate::chat_mls::call_links::CallLinkTokenRequest,
        crate::chat_mls::call_links::UpdateCallLinkInfoRequest,
        crate::chat_mls::call_links::CallLinkInfoRequest,
        crate::chat_mls::call_links::CallLinkInfoResponse,
        crate::chat_mls::call_link_waiting::SetWaitingRoomRequest,
        crate::chat_mls::call_link_waiting::KnockRequest,
        crate::chat_mls::call_link_waiting::KnockResponse,
        crate::chat_mls::call_link_waiting::KnockStatusRequest,
        crate::chat_mls::call_link_waiting::KnockStatusResponse,
        crate::chat_mls::call_link_moderation::HostCredentials,
        crate::chat_mls::call_link_moderation::MeetingRole,
        crate::chat_mls::call_link_moderation::MeetingRoles,
        crate::chat_mls::call_link_moderation::MuteRequest,
        crate::chat_mls::call_link_moderation::ScreenShareRequest,
        crate::chat_mls::call_link_moderation::LockRequest,
        crate::chat_mls::call_link_history::JoinedMeeting,
        crate::chat_mls::call_link_history::JoinedMeetingList,
        crate::chat_mls::call_link_moderation::SetCoHostRequest,
        crate::chat_mls::call_link_moderation::RemoveParticipantRequest,
        crate::chat_mls::call_link_waiting::WaitingKnock,
        crate::chat_mls::call_link_waiting::WaitingKnocks,
        crate::chat_mls::call_link_waiting::DecideKnockRequest,
        crate::handlers::chat_link_preview::LinkPreviewFetchResponse,
        crate::handlers::chat_link_preview::LinkPreviewFetchKind,
        kutup_chat_proto::ChatBackupCapabilitiesV1,
        kutup_chat_proto::ChatBackupSignerAuthorizationV1,
        kutup_chat_proto::ChatBackupManifestV1,
        kutup_chat_proto::ChatBackupStorageUsageV1,
        kutup_chat_proto::ChatBackupStatusV1,
        kutup_chat_proto::ChatBackupDeviceHeadV1,
        kutup_chat_proto::ProvisionChatBackupRequestV1,
        kutup_chat_proto::AppendChatBackupSegmentRequestV1,
        kutup_chat_proto::ChatBackupSegmentReceiptV1,
        kutup_chat_proto::ChatBackupWireSegmentV1,
        kutup_chat_proto::ChatBackupSegmentPageV1,
        kutup_chat_proto::ChatBackupBaseReceiptV1,
        kutup_chat_proto::CommitChatBackupManifestRequestV1,
        kutup_chat_proto::ChatBackupManifestCommitReceiptV1,
        kutup_chat_proto::CopyChatBackupMediaRequestV1,
        kutup_chat_proto::UploadChatBackupMediaRequestV1,
        kutup_chat_proto::ChatBackupMediaReceiptV1,
        kutup_chat_proto::ChatBackupMediaReferenceV1,
        kutup_chat_proto::ReconcileChatBackupMediaRequestV1,
        kutup_chat_proto::ChatBackupMediaReconciliationReceiptV1,
        kutup_federation_proto::FederationDiscoveryV2,
        kutup_federation_proto::FederationIdentityDocumentV1,
        kutup_chat_proto::FederatedChatTransaction,
        kutup_chat_proto::FederationDeliveryResponse,
        kutup_chat_proto::FederationDeliveryError,
        crate::drive_federation::RemoteDriveUserQuery,
        crate::drive_federation::RemoteDriveUserResponse,
        crate::drive_federation::CreateFederatedShareRequest,
        crate::drive_federation::CreateFederatedShareResponse,
        crate::drive_federation::DriveInviteResponse,
        crate::drive_federation::AcceptFederatedShareRequest,
        crate::drive_federation::IncomingDriveShare,
        crate::drive_profile_keys::PutProfileKeyRequest,
        crate::drive_profile_keys::DrivePeopleResponse,
        crate::drive_profile_keys::DrivePerson,
        crate::maps::MapSettings,
        crate::ui_preferences::UiPreferences,
        crate::handlers::name_hashes::ContentHashRequest,
        crate::handlers::name_hashes::NamedItem,
        crate::handlers::name_hashes::FillNameHashesRequest,
        crate::handlers::name_hashes::NameClash,
        crate::handlers::name_hashes::FillNameHashesResult,
        crate::photos::PhotosPreferences,
        crate::photos::PhotosLibraryRecord,
        crate::albums::AlbumRow,
        crate::albums::AlbumItem,
        crate::albums::AlbumItemInput,
        crate::albums::AddAlbumItems,
        crate::albums::RemoveAlbumItems,
        crate::albums::AlbumItemKey,
        crate::handlers::folder_access::KeptAlbumItem,
        crate::photos::PutPhotosLibrary,
        crate::handlers::file_shares::ShareFileRequest,
        crate::handlers::file_shares::FileAccessMember,
        crate::handlers::file_shares::FileAccess,
        crate::handlers::file_shares::MemberEnvelope,
        crate::handlers::file_shares::ResealRequest,
        crate::handlers::file_shares::RotateFileAccessRequest,
        crate::handlers::file_shares::SharedFile,
        crate::handlers::file_shares::MetadataAtShare,
        crate::handlers::file_shares::PendingFileShare,
        crate::handlers::file_shares::SharedByMeItem,
        crate::handlers::file_shares::FileSharingSettings,
        crate::drive_federation_files::CreateFederatedFileShareRequest,
        crate::drive_federation_files::CreateFederatedFileShareResponse,
        crate::drive_federation_files::FileInviteResponse,
        crate::drive_federation_files::FileStateResponse,
        crate::drive_federation_files::AcceptFederatedFileShareRequest,
        crate::drive_federation_files::IncomingFileShare,
        crate::drive_federation_files::IncomingFileShareNow,
        crate::handlers::file_shares::LinkEnvelope,
        crate::handlers::file_shares::FileLink,
        crate::handlers::file_shares::FederatedFileMember,
        crate::handlers::file_shares::FederatedEnvelope,
        crate::live_locations::CreateLiveLocationRequest,
        crate::live_locations::WriteLiveLocationRequest,
        crate::live_locations::LiveLocationResponse,
        crate::maps::CustomProvider,
        crate::maps::ProviderId,
        crate::maps::TileKind,
        crate::maps::ProxyMode,
        crate::maps::MapPreferences,
        crate::maps::MapProviderView,
        crate::maps::MapConfigResponse,
        crate::drive_profile_keys::FederatedProfileKey,
        crate::drive_federation::FederatedDriveFile,
        crate::drive_federation_albums::FederatedAlbumItem,
        crate::drive_federation::FederatedDriveUploadResponse,
        models::HealthResponse,
        models::ErrorResponse,
        models::MessageResponse,
        models::SettingsResponse,
        models::AdminSettingsResponse,
        models::PreflightLoginResponse,
        models::PreflightRecoverResponse,
        models::RefreshResponse,
        crate::config::AppOrigins,
        crate::handlers::sessions::SessionView,
        crate::handlers::sessions::CreateForkRequest,
        crate::handlers::sessions::CreateForkResponse,
        crate::handlers::sessions::ConsumeForkRequest,
        crate::handlers::sessions::ConsumeForkResponse,
        crate::handlers::sessions::LocalKeyBody,
        models::MeResponse,
        crate::handlers::storage::StorageUsageResponse,
        crate::handlers::storage::DriveUsage,
        crate::handlers::storage::ChatUsage,
        crate::handlers::storage::ContactsUsage,
        crate::handlers::storage::MailUsage,
        crate::handlers::mail_keys::OwnMailKey,
        crate::handlers::contacts::ContactRow,
        crate::handlers::contacts::ContactInput,
        crate::handlers::contacts::ContactPage,
        crate::handlers::contacts::ContactUpdate,
        crate::handlers::contacts::DeleteContacts,
        crate::handlers::contacts::ImportContacts,
        crate::handlers::contacts::ImportResult,
        crate::handlers::contacts::ContactEmailRow,
        crate::handlers::contacts::ContactGroupRow,
        crate::handlers::contacts::ContactGroupInput,
        crate::handlers::mail_keys::OwnMailAddress,
        crate::handlers::mail_keys::SignedKeyList,
        crate::handlers::mail_keys::AddMailKeyRequest,
        crate::handlers::mail_keys::PublicMailKey,
        crate::handlers::mail_keys::MailKeyLookup,
        crate::handlers::mail::MailMailbox,
        crate::handlers::mail::MailMessage,
        crate::handlers::mail::MailMessagePage,
        crate::handlers::mail::UpdateMailMessages,
        crate::handlers::mail::UpdatedMailMessages,
        crate::handlers::mail::DeleteMailMessages,
        crate::handlers::mail::MailFolderCount,
        crate::handlers::mail_send::MailboxInput,
        crate::handlers::mail_send::MailMeta,
        crate::handlers::mail_send::DraftAttachment,
        crate::handlers::mail_send::SendRecipient,
        crate::handlers::mail_send::SendResult,
        crate::handlers::mail_sending::MailSendingStatus,
        crate::handlers::mail_sending::MailSender,
        crate::handlers::mail_sending::UpdateMailSending,
        crate::handlers::storage::VersionAge,
        crate::handlers::storage::PruneVersionsRequest,
        crate::handlers::storage::PruneVersionsResponse,
        models::OkResponse,
        models::TotpSetupResponse,
        models::TotpCodeRequest,
        models::UserLookupResponse,
        models::CollectionRow,
        models::CreateCollectionRequest,
        models::CreateCollectionResult,
        models::UpdateCollectionRequest,
        models::UpdateColorRequest,
        models::ShareCollectionRequest,
        models::FileRow,
        models::FileThumbnails,
        models::UploadResult,
        models::TrashFolderRow,
        models::TrashFileRow,
        models::TrashResponse,
        models::CreateShareRequest,
        models::CreateShareResult,
        models::PublicShareResponse,
        models::UserRow,
        models::CreateAdminUserRequest,
        models::UpdateAdminUserRequest,
        models::UpdateAdminSettingsRequest,
        models::StatsResponse,
    )),
    modifiers(&BearerAuthAddon),
)]
pub struct ApiDoc;

/// Registers the `BearerAuth` security scheme — mirrors the Go
/// `@securityDefinitions.apikey BearerAuth` / `@in header` / `@name Authorization`.
struct BearerAuthAddon;

impl Modify for BearerAuthAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "BearerAuth",
                SecurityScheme::ApiKey(ApiKey::Header(ApiKeyValue::new("Authorization"))),
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use utoipa::OpenApi;

    use super::ApiDoc;

    /// Every HTTP operation registered in `build_router` (74 router entries → 78
    /// method+path pairs, counting each method on a multi-method route). Keep in sync
    /// with `paths(...)` above when routes change.
    const EXPECTED_OPERATIONS: usize = 91;

    #[test]
    fn spec_lists_every_router_operation() {
        let spec = serde_json::to_value(ApiDoc::openapi()).expect("spec serializes");
        let paths = spec["paths"].as_object().expect("paths object");

        const METHODS: [&str; 8] = [
            "get", "put", "post", "delete", "options", "head", "patch", "trace",
        ];
        let operations: usize = paths
            .values()
            .map(|item| {
                item.as_object()
                    .expect("path item object")
                    .keys()
                    .filter(|k| METHODS.contains(&k.as_str()))
                    .count()
            })
            .sum();
        assert!(
            operations >= EXPECTED_OPERATIONS,
            "spec lists {operations} operations, expected at least {EXPECTED_OPERATIONS} — \
             did a handler lose its #[utoipa::path] registration?"
        );

        // Spot-check key paths (one per route group).
        for path in [
            "/api/health",
            "/api/auth/login",
            "/api/collections/{id}/files",
            "/api/devices",
            "/api/uploads/{id}",
            "/api/files/{id}",
            "/api/trash",
            "/api/files/{fileId}/versions/{vid}",
            "/api/files/{fileId}/assets/{assetId}",
            "/api/files/{fileId}/collab/ws",
            "/api/share/{token}/download/{fileId}",
            "/api/fed/drive/files",
            "/api/drive/federation/shares/{shareId}/files",
            "/api/admin/activity",
            "/api/admin/activity/export",
            "/api/admin/users/{id}/rotate-temp-password",
            "/api/admin/users/{id}/wipe",
            "/api/admin/federation",
            "/api/admin/federation/rules/{feature}/{domain}",
            "/api/admin/federation/peers/{domain}/evidence",
            "/api/admin/federation/peers/{domain}/verify",
            "/api/admin/federation/peers/{domain}/retry",
            "/api/admin/federation/peers/retry",
            "/api/admin/federation/peers/{domain}/repin",
            "/api/chat/users/{username}/keys",
            "/api/chat/messages/ack",
            "/api/chat/ws",
            "/.well-known/kutup/federation.json",
            "/.well-known/kutup/federation/identity/{sequence}.json",
            "/api/fed/chat/users/{username}/keys",
            "/api/fed/chat/messages",
        ] {
            assert!(paths.contains_key(path), "spec is missing path {path}");
        }
    }

    #[test]
    fn direct_chat_suite_schema_is_a_closed_numeric_registry() {
        let spec = serde_json::to_value(ApiDoc::openapi()).expect("spec serializes");
        let schema = &spec["components"]["schemas"]["DirectChatSuiteId"];

        assert_eq!(schema["type"], "integer");
        assert_eq!(schema["enum"], serde_json::json!([1]));
    }
}
