CREATE TABLE files (
    -- Generated by the encrypting client before envelope construction.
    id                    UUID PRIMARY KEY,
    collection_id         UUID NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
    uploader_user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- DriveEnvelopeV1 records bound to file, collection and collection epoch.
    metadata_envelope     TEXT NOT NULL,
    file_key_envelope     TEXT NOT NULL,
    key_epoch             INTEGER NOT NULL CHECK (key_epoch > 0),
    metadata_revision     BIGINT NOT NULL DEFAULT 1 CHECK (metadata_revision > 0),
    -- Storage path in SeaweedFS: {userId}/{collectionId}/{fileId}
    storage_path          TEXT NOT NULL,
    -- Encrypted file size (actual bytes stored in SeaweedFS, for quota tracking)
    encrypted_size_bytes  BIGINT NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_files_collection ON files(collection_id);
CREATE INDEX idx_files_uploader ON files(uploader_user_id);
