// Rendered markdown preview pane for the notes editor's Split / Read modes.
//
// react-markdown does the AST + JSX render. Plugin chain:
// - remark-gfm: GitHub-Flavored Markdown (tables, task lists, strikethrough,
//   autolinks, footnotes). Matches what most users expect when they write .md.
// - remark-breaks: turn single newlines into hard line breaks. CommonMark
//   defaults to soft breaks (rendered as a space inside a paragraph), which
//   surprises users who expect "Enter = new line" like a normal editor.
// - remark-math: parse `$inline$` and `$$block$$` math syntax into HAST nodes
//   that rehype-katex then renders.
// - rehype-sanitize: defense-in-depth XSS protection for user-authored
//   content. Notes are E2EE so the server never sees plaintext, but a
//   collaborator could embed <script> tags that fire on view. Runs FIRST
//   so the sanitized HAST is what subsequent rehype plugins receive.
// - rehype-katex: render math nodes from remark-math via KaTeX. Runs AFTER
//   sanitize because katex output is generated by trusted code (not user
//   input); sanitizing it would strip katex's own classes + MathML.
// - rehype-highlight: code-block syntax highlighting using highlight.js.
//
// Mermaid: rendered via a custom `pre` component that detects `language-
// mermaid` fences and runs `mermaid.render()` client-side. The SVG output
// is parsed via DOMParser and appended to a ref'd container — avoids
// dangerouslySetInnerHTML. mermaid is initialized with securityLevel:
// 'strict' which sanitizes diagram source.
//
// Styling: Tailwind's @tailwindcss/typography `prose` classes + KaTeX's
// shipped CSS for math.
//
// Scroll sync: the parent passes a controlled scroll percentage; we apply
// it to the inner scroll container in a useEffect. Onscroll, we report the
// pane's own percentage so the parent can mirror back to the editor.
//
// Interactive task lists: by default react-markdown renders `- [ ]` /
// `- [x]` checkboxes as `disabled`. We override the `input` component to
// strip disabled and wire onChange — the parent receives (index, checked)
// and is expected to mutate the source markdown (typically via Yjs).

import { useEffect, useId, useRef, useState, isValidElement } from 'react'
import type { ReactElement, ReactNode } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import remarkBreaks from 'remark-breaks'
import remarkMath from 'remark-math'
import rehypeSanitize from 'rehype-sanitize'
import rehypeKatex from 'rehype-katex'
import rehypeHighlight from 'rehype-highlight'
import mermaid from 'mermaid'
import 'katex/dist/katex.min.css'

// Initialize mermaid once at module load. `securityLevel: 'strict'` is
// the default in v11 but we set it explicitly — diagram source comes
// from the document content which a collaborator could craft.
mermaid.initialize({ startOnLoad: false, securityLevel: 'strict', theme: 'default' })

interface Props {
  source: string
  /** 0..1 desired scroll position. Parent drives this when in Split mode. */
  scrollPercent?: number
  /** Notify parent of the user's own scroll inside this pane. */
  onScrollPercent?: (p: number) => void
  /** Toggle the Nth GFM task-list checkbox (0-based, document order).
   *  Caller is responsible for mutating the source string. */
  onToggleTaskList?: (index: number, checked: boolean) => void
  className?: string
}

// MermaidBlock renders a mermaid diagram source string into SVG and
// mounts it as a real DOM node. Avoids dangerouslySetInnerHTML by
// parsing mermaid's output via DOMParser and appending the resulting
// SVGElement directly. Render failures show a readable error.
function MermaidBlock({ source }: { source: string }) {
  // Mermaid IDs must be DOM-id-safe; useId returns ":r0:"-style strings,
  // which mermaid chokes on. Strip the colons.
  const id = `mmd-${useId().replace(/[:]/g, '_')}`
  const containerRef = useRef<HTMLDivElement>(null)
  const [err, setErr] = useState<string>('')

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        const out = await mermaid.render(id, source)
        if (cancelled) return
        const container = containerRef.current
        if (!container) return
        // Parse the SVG string into a real DOM tree (XML) and append.
        // This is functionally equivalent to setting innerHTML but
        // pushes parsing into the standardized DOMParser path and
        // avoids the dangerouslySetInnerHTML React API.
        const parser = new DOMParser()
        const doc = parser.parseFromString(out.svg, 'image/svg+xml')
        const svgEl = doc.documentElement
        // DOMParser returns a parsererror element on failure.
        if (svgEl.nodeName === 'parsererror') {
          setErr('mermaid output failed to parse')
          return
        }
        container.replaceChildren(svgEl)
        setErr('')
      } catch (e) {
        if (!cancelled) {
          setErr(e instanceof Error ? e.message : String(e))
          containerRef.current?.replaceChildren()
        }
      }
    })()
    return () => { cancelled = true }
  }, [source, id])

  if (err) {
    return (
      <pre className="text-destructive whitespace-pre-wrap text-xs">
        Mermaid error: {err}
      </pre>
    )
  }
  return <div ref={containerRef} className="not-prose flex justify-center" />
}

export default function MarkdownPreview({
  source,
  scrollPercent,
  onScrollPercent,
  onToggleTaskList,
  className,
}: Props) {
  const scrollRef = useRef<HTMLDivElement>(null)
  // Suppress the next scroll-event echo when the parent drives our position
  // (otherwise we'd report-back and create a feedback loop).
  const ignoreNextScroll = useRef(false)
  // Per-render checkbox counter. Reset on every render of MarkdownPreview
  // so each task-list <input> gets the right document-order index. React
  // calls our component function fresh per source change, so this works.
  const taskCounter = useRef(0)
  taskCounter.current = 0

  // Apply controlled scroll percent from parent.
  useEffect(() => {
    if (scrollPercent == null) return
    const el = scrollRef.current
    if (!el) return
    const max = el.scrollHeight - el.clientHeight
    if (max <= 0) return
    const target = Math.round(max * scrollPercent)
    if (Math.abs(el.scrollTop - target) < 2) return
    ignoreNextScroll.current = true
    el.scrollTop = target
  }, [scrollPercent])

  function handleScroll() {
    if (ignoreNextScroll.current) {
      ignoreNextScroll.current = false
      return
    }
    if (!onScrollPercent) return
    const el = scrollRef.current
    if (!el) return
    const max = el.scrollHeight - el.clientHeight
    if (max <= 0) {
      onScrollPercent(0)
      return
    }
    onScrollPercent(el.scrollTop / max)
  }

  return (
    <div
      ref={scrollRef}
      onScroll={handleScroll}
      className={
        'overflow-auto px-6 py-4 ' +
        'prose prose-sm dark:prose-invert max-w-none ' +
        // Make code-block + inline-code visible against both themes.
        'prose-code:before:hidden prose-code:after:hidden ' +
        (className ?? '')
      }
    >
      <ReactMarkdown
        remarkPlugins={[remarkGfm, remarkBreaks, remarkMath]}
        rehypePlugins={[rehypeSanitize, rehypeKatex, rehypeHighlight]}
        components={{
          input(props) {
            if (props.type !== 'checkbox') {
              // eslint-disable-next-line jsx-a11y/no-redundant-roles
              return <input {...props} />
            }
            const idx = taskCounter.current++
            return (
              <input
                type="checkbox"
                checked={!!props.checked}
                onChange={(e) => onToggleTaskList?.(idx, e.target.checked)}
                className="cursor-pointer mr-1.5 align-middle"
              />
            )
          },
          // Detect ` ```mermaid ` fenced blocks and render via the mermaid
          // package. Other languages fall through to the default <pre>.
          // We override `pre` (not `code`) so we replace the whole code-
          // block container, not just the inline <code>.
          pre(props) {
            const child = (props.children as ReactNode | undefined)
            if (isValidElement(child)) {
              const codeEl = child as ReactElement<{ className?: string; children?: ReactNode }>
              const cls = codeEl.props.className ?? ''
              if (cls.includes('language-mermaid')) {
                const src = String(codeEl.props.children ?? '').replace(/\n$/, '')
                return <MermaidBlock source={src} />
              }
            }
            return <pre {...props} />
          },
        }}
      >
        {source}
      </ReactMarkdown>
    </div>
  )
}
