//! Cross-language parity tests: verify that `kutup-crypto` (Rust) produces and
//! accepts byte-for-byte the same outputs as the Go reference packages
//! (`cmd/kutup/internal/crypto`, `backend/services/envelope`).
//!
//! The vectors in `tests/vectors/*.json` are generated by the `genvectors`
//! tools in each Go module — see those programs to regenerate after a change.

use base64::Engine;
use serde::Deserialize;

use kutup_crypto::{asset, envelope, kdf, sealedbox, secretbox, stream};

fn b64(s: &str) -> Vec<u8> {
    base64::engine::general_purpose::STANDARD
        .decode(s)
        .expect("valid base64")
}

#[derive(Deserialize)]
struct CryptoVectors {
    kdf: Vec<KdfVec>,
    hkdf: Vec<HkdfVec>,
    secretbox: Vec<SecretboxVec>,
    sealedbox: Vec<SealedboxVec>,
    stream: Vec<StreamVec>,
    asset: Vec<AssetVec>,
}

#[derive(Deserialize)]
struct KdfVec {
    password: String,
    salt: String,
    expected: String,
}
#[derive(Deserialize)]
struct HkdfVec {
    master: String,
    #[serde(rename = "fileId")]
    file_id: String,
    expected: String,
}
#[derive(Deserialize)]
struct SecretboxVec {
    key: String,
    nonce: String,
    plaintext: String,
    ciphertext: String,
}
#[derive(Deserialize)]
struct SealedboxVec {
    #[serde(rename = "recipientPub")]
    recipient_pub: String,
    #[serde(rename = "recipientPriv")]
    recipient_priv: String,
    plaintext: String,
    sealed: String,
}
#[derive(Deserialize)]
struct StreamVec {
    key: String,
    plaintext: String,
    ciphertext: String,
}
#[derive(Deserialize)]
struct AssetVec {
    master: String,
    #[serde(rename = "fileId")]
    file_id: String,
    #[serde(rename = "assetId")]
    asset_id: String,
    plaintext: String,
    blob: String,
}

fn load_crypto() -> CryptoVectors {
    let raw = include_str!("vectors/crypto.json");
    serde_json::from_str(raw).expect("parse crypto.json")
}

#[test]
fn kdf_matches_go() {
    for v in load_crypto().kdf {
        let salt = b64(&v.salt);
        let expected = b64(&v.expected);
        // Argon2id is deterministic — derive_kek and derive_login_key share params.
        let kek = kdf::derive_kek(&v.password, &salt).unwrap();
        assert_eq!(kek.as_slice(), &expected[..], "derive_kek mismatch");
        let login = kdf::derive_login_key(&v.password, &salt).unwrap();
        assert_eq!(login.as_slice(), &expected[..], "derive_login_key mismatch");
    }
}

#[test]
fn hkdf_content_key_matches_go() {
    for v in load_crypto().hkdf {
        let key = kdf::derive_content_key(&b64(&v.master), &v.file_id).unwrap();
        assert_eq!(
            key.as_slice(),
            &b64(&v.expected)[..],
            "content key mismatch"
        );
    }
}

#[test]
fn secretbox_matches_go() {
    for v in load_crypto().secretbox {
        let (key, nonce, plain, ct) = (
            b64(&v.key),
            b64(&v.nonce),
            b64(&v.plaintext),
            b64(&v.ciphertext),
        );
        // Encrypt direction (fixed nonce) reproduces the Go ciphertext exactly.
        let got = secretbox::seal_with_nonce(&plain, &nonce, &key).unwrap();
        assert_eq!(got, ct, "secretbox ciphertext mismatch");
        // Decrypt direction recovers the plaintext.
        let dec = secretbox::open(&ct, &nonce, &key).unwrap();
        assert_eq!(dec, plain, "secretbox plaintext mismatch");
    }
}

#[test]
fn sealedbox_opens_go_output() {
    for v in load_crypto().sealedbox {
        let dec = sealedbox::open_anonymous(
            &b64(&v.sealed),
            &b64(&v.recipient_pub),
            &b64(&v.recipient_priv),
        )
        .unwrap();
        assert_eq!(dec, b64(&v.plaintext), "sealed box plaintext mismatch");
    }
}

#[test]
fn stream_decrypts_go_output() {
    for v in load_crypto().stream {
        let dec = stream::decrypt_stream(&b64(&v.ciphertext), &b64(&v.key)).unwrap();
        assert_eq!(dec, b64(&v.plaintext), "stream plaintext mismatch");
    }
}

#[test]
fn asset_decrypts_go_output() {
    for v in load_crypto().asset {
        let dec =
            asset::decrypt_asset(&b64(&v.blob), &v.file_id, &v.asset_id, &b64(&v.master)).unwrap();
        assert_eq!(dec, b64(&v.plaintext), "asset plaintext mismatch");
    }
}

// --- Rust-only round-trips that complement the Go-cross vectors -------------

#[test]
fn sealedbox_roundtrip() {
    // Use a known recipient from the vectors to exercise the seal direction.
    let v = &load_crypto().sealedbox[0];
    let (pub_k, priv_k) = (b64(&v.recipient_pub), b64(&v.recipient_priv));
    let msg = b"round-trip payload";
    let sealed = sealedbox::seal_anonymous(msg, &pub_k).unwrap();
    let opened = sealedbox::open_anonymous(&sealed, &pub_k, &priv_k).unwrap();
    assert_eq!(opened, msg);
}

#[test]
fn stream_multichunk_roundtrip() {
    // Exercise the 5 MiB chunk boundary (intermediate TAG_MESSAGE + final).
    let key = [0x33u8; 32];
    let plain: Vec<u8> = (0..stream::CHUNK_SIZE + 1)
        .map(|i| (i % 251) as u8)
        .collect();
    let ct = stream::encrypt_stream(&plain, &key).unwrap();
    // header + 2 chunks: (CHUNK_SIZE + 1) plaintext + 2*ABYTES overhead.
    assert_eq!(
        ct.len(),
        stream::HEADER_BYTES + plain.len() + 2 * stream::ABYTES,
        "expected exactly two chunks",
    );
    let dec = stream::decrypt_stream(&ct, &key).unwrap();
    assert_eq!(dec, plain);
}

#[test]
fn stream_tamper_fails() {
    let key = [0x33u8; 32];
    let mut ct = stream::encrypt_stream(b"sensitive content", &key).unwrap();
    let n = ct.len();
    ct[n / 2] ^= 0xff;
    assert!(stream::decrypt_stream(&ct, &key).is_err());
}

#[test]
fn asset_tamper_and_aad_fail() {
    let master = [0xCDu8; 32];
    let blob = asset::encrypt_asset(b"payload", "fid", "asset", &master).unwrap();
    // Wrong assetId (AAD) and wrong fileId (HKDF info) must both fail.
    assert!(asset::decrypt_asset(&blob, "fid", "other", &master).is_err());
    assert!(asset::decrypt_asset(&blob, "other", "asset", &master).is_err());
    // Tampered ciphertext fails.
    let mut bad = blob.clone();
    let n = bad.len();
    bad[n - 1] ^= 0xff;
    assert!(asset::decrypt_asset(&bad, "fid", "asset", &master).is_err());
}

// --- envelope -------------------------------------------------------------

#[derive(Deserialize)]
struct EnvVec {
    seed: String,
    pub_: String,
    version: u8,
    kind: u8,
    #[serde(rename = "docKeyId")]
    doc_key_id: u32,
    #[serde(rename = "senderDeviceId")]
    sender_device_id: u64,
    sequence: u64,
    nonce: String,
    ciphertext: String,
    packed: String,
}

// `pub` is a keyword; remap the JSON field.
impl EnvVec {
    fn from_value(v: serde_json::Value) -> Self {
        serde_json::from_value(rename_pub(v)).unwrap()
    }
}
fn rename_pub(mut v: serde_json::Value) -> serde_json::Value {
    if let Some(obj) = v.as_object_mut() {
        if let Some(p) = obj.remove("pub") {
            obj.insert("pub_".into(), p);
        }
    }
    v
}

#[test]
fn envelope_matches_go() {
    let raw = include_str!("vectors/envelope.json");
    let values: Vec<serde_json::Value> = serde_json::from_str(raw).expect("parse envelope.json");
    for value in values {
        let v = EnvVec::from_value(value);
        let nonce: [u8; 24] = b64(&v.nonce).try_into().unwrap();
        let frame = envelope::Frame {
            version: v.version,
            kind: v.kind,
            doc_key_id: v.doc_key_id,
            sender_device_id: v.sender_device_id,
            sequence: v.sequence,
            nonce,
            ciphertext: b64(&v.ciphertext),
            signature: [0u8; 64],
        };
        let packed = b64(&v.packed);
        let pub_k = b64(&v.pub_);

        // Sign direction (Ed25519 is deterministic) reproduces Go's wire bytes.
        let signed = envelope::sign(&frame, &b64(&v.seed)).unwrap();
        assert_eq!(signed, packed, "envelope packed/sign mismatch");

        // Unpack round-trips the fields and re-packs identically.
        let parsed = envelope::Frame::unpack(&packed).unwrap();
        assert_eq!(parsed.version, v.version);
        assert_eq!(parsed.kind, v.kind);
        assert_eq!(parsed.doc_key_id, v.doc_key_id);
        assert_eq!(parsed.sender_device_id, v.sender_device_id);
        assert_eq!(parsed.sequence, v.sequence);
        assert_eq!(parsed.nonce, nonce);
        assert_eq!(parsed.ciphertext, b64(&v.ciphertext));
        assert_eq!(parsed.pack(), packed);

        // Signature verifies; a flipped body byte fails.
        envelope::verify(&packed, &pub_k).unwrap();
        let mut tampered = packed.clone();
        tampered[0] ^= 0x01;
        assert!(envelope::verify(&tampered, &pub_k).is_err());
    }
}
