// Rendered markdown preview pane for the notes editor's Split / Read modes.
//
// react-markdown does the AST + JSX render. Plugin chain:
// - remark-gfm: GitHub-Flavored Markdown (tables, task lists, strikethrough,
//   autolinks, footnotes). Matches what most users expect when they write .md.
// - remark-breaks: turn single newlines into hard line breaks. CommonMark
//   defaults to soft breaks (rendered as a space inside a paragraph), which
//   surprises users who expect "Enter = new line" like a normal editor.
// - remark-math: parse `$inline$` and `$$block$$` math syntax into HAST nodes
//   that rehype-katex then renders.
// - rehype-sanitize: defense-in-depth XSS protection for user-authored
//   content. Notes are E2EE so the server never sees plaintext, but a
//   collaborator could embed <script> tags that fire on view. Runs FIRST
//   so the sanitized HAST is what subsequent rehype plugins receive.
// - rehype-katex: render math nodes from remark-math via KaTeX. Runs AFTER
//   sanitize because katex output is generated by trusted code (not user
//   input); sanitizing it would strip katex's own classes + MathML.
// - rehype-highlight: code-block syntax highlighting using highlight.js.
// - code blocks (codeBlocks.ts): a copy button on each, and the fence
//   options `title="…"`, `showLineNumbers` and `{2,4-6}` (highlighted
//   lines), in the convention docs sites share.
//
// Mermaid: rendered via a custom `pre` component that detects `language-
// mermaid` fences and runs `mermaid.render()` client-side. The SVG output
// is parsed via DOMParser and appended to a ref'd container — avoids
// dangerouslySetInnerHTML. mermaid is initialized with securityLevel:
// 'strict' which sanitizes diagram source.
//
// Styling: Tailwind's @tailwindcss/typography `prose` classes + KaTeX's
// shipped CSS for math.
//
// Scroll sync: the parent passes a controlled scroll percentage; we apply
// it to the inner scroll container in a useEffect. Onscroll, we report the
// pane's own percentage so the parent can mirror back to the editor.
//
// Interactive task lists: by default react-markdown renders `- [ ]` /
// `- [x]` checkboxes as `disabled`. We override the `input` component to
// strip disabled and wire onChange — the parent receives (index, checked)
// and is expected to mutate the source markdown (typically via Yjs).

import { useEffect, useId, useRef, useState, isValidElement } from 'react'
import type { ComponentProps, MutableRefObject, ReactElement, ReactNode } from 'react'
import { Checkbox } from '@kutup/ui/components/checkbox'
import ReactMarkdown, { defaultUrlTransform } from 'react-markdown'
import remarkGfm from 'remark-gfm'
import remarkBreaks from 'remark-breaks'
import remarkMath from 'remark-math'
import rehypeSanitize from 'rehype-sanitize'
import rehypeKatex from 'rehype-katex'
import rehypeHighlight from 'rehype-highlight'
import mermaid from 'mermaid'
import {
  Bug, Check, CircleCheck, CircleHelp, ClipboardList, Copy, Flame, Info, List, Pencil, Quote, TriangleAlert, X, Zap,
  type LucideIcon,
} from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { rehypeCodeLines, remarkCodeMeta, sanitizeSchema } from './codeBlocks'
import { calloutKind, remarkCallouts, remarkHighlight, type CalloutKind } from './callouts'
import { assetIdFromSrc } from '../noteImages'
import { parseKutupHref } from '../links/kutupLinks'
import 'katex/dist/katex.min.css'

// Initialize mermaid once at module load. `securityLevel: 'strict'` is
// the default in v11 but we set it explicitly — diagram source comes
// from the document content which a collaborator could craft.
mermaid.initialize({ startOnLoad: false, securityLevel: 'strict', theme: 'default' })

interface Props {
  source: string
  /** 0..1 desired scroll position. Parent drives this when in Split mode. */
  scrollPercent?: number
  /** Notify parent of the user's own scroll inside this pane. */
  onScrollPercent?: (p: number) => void
  /** Toggle the Nth GFM task-list checkbox (0-based, document order).
   *  Caller is responsible for mutating the source string. */
  onToggleTaskList?: (index: number, checked: boolean) => void
  className?: string
  /** Set to the scrolling container (the outline scrolls it to a heading). */
  containerRef?: MutableRefObject<HTMLDivElement | null>
  /** Opens the note's own images (`kutup:asset/…`) as blob: URLs; absent, they show as unavailable. */
  resolveAsset?: (assetId: string) => Promise<string | null>
  /** Opens a picture in Drive linked as `![…](kutup:file/…)`. */
  resolveFileImage?: (fileId: string) => Promise<string | null>
  /** Draws a link to a Kutup item (`kutup:file/…`, `kutup:folder/…`). */
  renderKutupLink?: (href: string, children: ReactNode) => ReactNode
}

/** The text inside rendered children (a code block's source). */
function textOf(node: ReactNode): string {
  if (typeof node === 'string' || typeof node === 'number') return String(node)
  if (Array.isArray(node)) return node.map(textOf).join('')
  if (isValidElement<{ children?: ReactNode }>(node)) return textOf(node.props.children)
  return ''
}

/** A note's own image: opened in the browser, shown once it is. */
function NoteImage({ assetId, alt, resolve }: { assetId: string; alt: string; resolve?: (id: string) => Promise<string | null> }) {
  const { t } = useTranslation()
  const [url, setUrl] = useState<string | null | undefined>(undefined)
  useEffect(() => {
    let alive = true
    setUrl(undefined)
    if (!resolve) {
      setUrl(null)
      return
    }
    void resolve(assetId).then((u) => alive && setUrl(u))
    return () => {
      alive = false
    }
  }, [assetId, resolve])
  if (url === undefined) {
    return <span className="note-image-pending" role="img" aria-label={alt || t('editor.image.loading')} />
  }
  if (url === null) {
    return <span className="note-image-missing">{t('editor.image.unavailable')}</span>
  }
  return <img src={url} alt={alt} className="note-image" />
}

function keepKutupUrls(url: string): string {
  return /^kutup:[a-z]+\/[\w-]+$/.test(url) ? url : defaultUrlTransform(url)
}

/** Obsidian's icon for each callout kind. */
const CALLOUT_ICONS: Record<CalloutKind, LucideIcon> = {
  note: Pencil, abstract: ClipboardList, info: Info, todo: CircleCheck, tip: Flame, success: Check,
  question: CircleHelp, warning: TriangleAlert, failure: X, danger: Zap, bug: Bug, example: List, quote: Quote,
}

/** How long "Copied" shows. */
const COPIED_MS = 1500

/**
 * A code block: its title bar when the fence names one, and a copy button
 * (the code as written: line numbers are drawn by CSS, not text).
 */
function CodeBlock({ pre, title }: { pre: ComponentProps<'pre'>; title: string | null }) {
  const { t } = useTranslation()
  const preRef = useRef<HTMLPreElement>(null)
  const [copied, setCopied] = useState(false)
  useEffect(() => {
    if (!copied) return
    const timer = setTimeout(() => setCopied(false), COPIED_MS)
    return () => clearTimeout(timer)
  }, [copied])

  async function copy() {
    const code = preRef.current?.querySelector('code')
    if (!code) return
    try {
      await navigator.clipboard.writeText(code.innerText.replace(/\n$/, ''))
      setCopied(true)
    } catch {
      // No clipboard access (an insecure context or a denied permission):
      // the code can still be selected by hand.
    }
  }

  // react-markdown's hast node is not a DOM attribute.
  const rest: ComponentProps<'pre'> & { node?: unknown } = { ...pre }
  delete rest.node
  return (
    <div className="code-block">
      {title ? <div className="code-block-title">{title}</div> : null}
      <div className="code-block-body">
        <pre ref={preRef} {...rest} className={title ? 'has-title' : undefined} />
        <button
        type="button"
        onClick={() => void copy()}
        aria-label={copied ? t('editor.code.copied') : t('editor.code.copy')}
        title={copied ? t('editor.code.copied') : t('editor.code.copy')}
        className="code-block-copy"
      >
          {copied ? <Check className="size-3.5" aria-hidden /> : <Copy className="size-3.5" aria-hidden />}
        </button>
      </div>
    </div>
  )
}

// MermaidBlock renders a mermaid diagram source string into SVG and
// mounts it as a real DOM node. Avoids dangerouslySetInnerHTML by
// parsing mermaid's output via DOMParser and appending the resulting
// SVGElement directly. Render failures show a readable error.
function MermaidBlock({ source }: { source: string }) {
  // Mermaid IDs must be DOM-id-safe; useId returns ":r0:"-style strings,
  // which mermaid chokes on. Strip the colons.
  const id = `mmd-${useId().replace(/[:]/g, '_')}`
  const containerRef = useRef<HTMLDivElement>(null)
  const [err, setErr] = useState<string>('')

  useEffect(() => {
    let cancelled = false
    void (async () => {
      try {
        const out = await mermaid.render(id, source)
        if (cancelled) return
        const container = containerRef.current
        if (!container) return
        // Parse the SVG string into a real DOM tree (XML) and append.
        // This is functionally equivalent to setting innerHTML but
        // pushes parsing into the standardized DOMParser path and
        // avoids the dangerouslySetInnerHTML React API.
        const parser = new DOMParser()
        const doc = parser.parseFromString(out.svg, 'image/svg+xml')
        const svgEl = doc.documentElement
        // DOMParser returns a parsererror element on failure.
        if (svgEl.nodeName === 'parsererror') {
          setErr('mermaid output failed to parse')
          return
        }
        container.replaceChildren(svgEl)
        setErr('')
      } catch (e) {
        if (!cancelled) {
          setErr(e instanceof Error ? e.message : String(e))
          containerRef.current?.replaceChildren()
        }
      }
    })()
    return () => { cancelled = true }
  }, [source, id])

  if (err) {
    return (
      <pre className="text-destructive whitespace-pre-wrap text-xs">
        Mermaid error: {err}
      </pre>
    )
  }
  return <div ref={containerRef} className="not-prose flex justify-center" />
}

export default function MarkdownPreview({
  source,
  scrollPercent,
  onScrollPercent,
  onToggleTaskList,
  className,
  containerRef,
  resolveAsset,
  resolveFileImage,
  renderKutupLink,
}: Props) {
  const scrollRef = useRef<HTMLDivElement | null>(null)
  const { t } = useTranslation()
  const calloutLabel = (kind: CalloutKind) => t(`editor.callout.${kind}`)
  // Suppress the next scroll-event echo when the parent drives our position
  // (otherwise we'd report-back and create a feedback loop).
  const ignoreNextScroll = useRef(false)
  // Per-render checkbox counter. Reset on every render of MarkdownPreview
  // so each task-list <input> gets the right document-order index. React
  // calls our component function fresh per source change, so this works.
  const taskCounter = useRef(0)
  taskCounter.current = 0

  // Apply controlled scroll percent from parent.
  useEffect(() => {
    if (scrollPercent == null) return
    const el = scrollRef.current
    if (!el) return
    const max = el.scrollHeight - el.clientHeight
    if (max <= 0) return
    const target = Math.round(max * scrollPercent)
    if (Math.abs(el.scrollTop - target) < 2) return
    ignoreNextScroll.current = true
    el.scrollTop = target
  }, [scrollPercent])

  function handleScroll() {
    if (ignoreNextScroll.current) {
      ignoreNextScroll.current = false
      return
    }
    if (!onScrollPercent) return
    const el = scrollRef.current
    if (!el) return
    const max = el.scrollHeight - el.clientHeight
    if (max <= 0) {
      onScrollPercent(0)
      return
    }
    onScrollPercent(el.scrollTop / max)
  }

  return (
    <div
      ref={(el) => {
        scrollRef.current = el
        if (containerRef) containerRef.current = el
      }}
      onScroll={handleScroll}
      className={
        'overflow-auto py-4 ' +
        'prose prose-sm max-w-none ' +
        // Make code-block + inline-code visible against both themes.
        'prose-code:before:hidden prose-code:after:hidden ' +
        (className ?? '')
      }
    >
      {/* The same measure as Edit mode's text (NOTE_LAYOUT in TextCollabEditor), centred. */}
      <div className="mx-auto max-w-[40rem] px-6">
      <ReactMarkdown
        remarkPlugins={[remarkGfm, remarkBreaks, remarkMath, remarkCodeMeta, remarkHighlight, [remarkCallouts, { label: calloutLabel }]]}
        rehypePlugins={[[rehypeSanitize, sanitizeSchema], rehypeKatex, rehypeHighlight, rehypeCodeLines]}
        // `kutup:` links (a note's own images, Kutup items) are resolved here;
        // every other URL goes through react-markdown's safe-protocol filter.
        urlTransform={keepKutupUrls}

        components={{
          input(props) {
            if (props.type !== 'checkbox') return <input {...props} />
            // A GFM task-list item; its text follows in the same list item.
            const idx = taskCounter.current++
            return (
              <Checkbox
                checked={Boolean(props.checked)}
                disabled={!onToggleTaskList}
                onCheckedChange={(checked) => onToggleTaskList?.(idx, checked === true)}
                className="mr-1.5 align-middle"
              />
            )
          },
          img(props) {
            // react-markdown's hast node is not a DOM attribute.
            const rest: ComponentProps<'img'> & { node?: unknown } = { ...props }
            delete rest.node
            const src = typeof rest.src === 'string' ? rest.src : undefined
            const assetId = assetIdFromSrc(src)
            if (assetId) return <NoteImage assetId={assetId} alt={rest.alt ?? ''} resolve={resolveAsset} />
            const linked = parseKutupHref(src)
            if (linked?.type === 'file') return <NoteImage assetId={linked.id} alt={rest.alt ?? ''} resolve={resolveFileImage} />
            return <img {...rest} />
          },
          div(props) {
            const rest: ComponentProps<'div'> & { node?: unknown; 'data-callout'?: string } = { ...props }
            delete rest.node
            const cls = typeof rest.className === 'string' ? rest.className : ''
            if (cls.split(' ').includes('callout-title')) {
              const Icon = CALLOUT_ICONS[calloutKind(rest['data-callout'] ?? 'note')]
              return (
                <div {...rest}>
                  <Icon className="callout-icon" aria-hidden />
                  <span>{rest.children}</span>
                </div>
              )
            }
            return <div {...rest} />
          },
          a(props) {
            const rest: ComponentProps<'a'> & { node?: unknown } = { ...props }
            delete rest.node
            if (parseKutupHref(rest.href) && renderKutupLink) return renderKutupLink(rest.href!, rest.children)
            return <a {...rest} />
          },
          // Detect ` ```mermaid ` fenced blocks and render via the mermaid
          // package. Other languages fall through to the default <pre>.
          // We override `pre` (not `code`) so we replace the whole code-
          // block container, not just the inline <code>.
          pre(props) {
            const child = (props.children as ReactNode | undefined)
            if (isValidElement(child)) {
              const codeEl = child as ReactElement<{ className?: string; children?: ReactNode }>
              const cls = codeEl.props.className ?? ''
              if (cls.includes('language-mermaid')) {
                const src = textOf(codeEl.props.children).replace(/\n$/, '')
                return <MermaidBlock source={src} />
              }
              const title = (codeEl.props as Record<string, unknown>)['data-title']
              return <CodeBlock pre={props} title={typeof title === 'string' ? title : null} />
            }
            return <pre {...props} />
          },
        }}
      >
        {source}
      </ReactMarkdown>
      </div>
    </div>
  )
}
